name: Create live linux kit

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: "build kit"
        id: kit_live
        run: sudo bash ./build
